# **Features engineering**

In [205]:
# Import libraries
from pathlib import Path
import pandas as pd
import numpy as np

In [206]:
# Loading the data
input_path = Path("..") / 'data' / 'raw' / 'dataset.csv'
df = pd.read_csv(input_path)
display(df.head(5))
print("Shape of the piezometer dataframe:\n", df.shape)

,code_bss,bss_id,date_index,niveau_nappe_eau,mode_obtention,nom_producteur,latitude,longitude,sunrise,sunset,daylight_duration,precipitation_sum,shortwave_radiation_sum,et0_fao_evapotranspiration,cloud_cover_mean,pressure_msl_mean,wind_speed_10m_mean,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean
0,10906X0039/C2-1,BSS002MNYD,2017-01-01,101.85,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-01T07:19,2017-01-01T16:26,32800.70,0.0,7.88,0.95,47,1024.5,5.3,0.244,9.2
1,10906X0039/C2-1,BSS002MNYD,2017-01-02,101.89,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-02T07:19,2017-01-02T16:27,32850.58,0.0,4.29,0.56,93,1022.0,4.6,0.244,9.2
2,10906X0039/C2-1,BSS002MNYD,2017-01-03,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-03T07:19,2017-01-03T16:28,32904.28,0.0,8.02,1.59,3,1023.5,11.8,0.244,8.9
3,10906X0039/C2-1,BSS002MNYD,2017-01-04,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-04T07:19,2017-01-04T16:29,32961.75,0.0,8.08,2.52,5,1022.9,25.2,0.244,8.8
4,10906X0039/C2-1,BSS002MNYD,2017-01-05,102.01,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-05T07:19,2017-01-05T16:30,33022.91,0.0,6.93,2.07,14,1026.5,30.5,0.243,8.7

Shape of the piezometer dataframe:
 (3405, 19)

In [207]:
df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['code_bss', 'bss_id', 'date_index', 'niveau_nappe_eau',
       'mode_obtention', 'nom_producteur', 'latitude', 'longitude', 'sunrise',
       'sunset', 'daylight_duration', 'precipitation_sum',
       'shortwave_radiation_sum', 'et0_fao_evapotranspiration',
       'cloud_cover_mean', 'pressure_msl_mean', 'wind_speed_10m_mean',
       'soil_moisture_0_to_100cm_mean', 'soil_temperature_0_to_100cm_mean'],
      dtype='str')>

In [208]:
# Index define as date_index
df["date_index"] = pd.to_datetime(df["date_index"])
df = df.set_index("date_index")
display(df.head(5))

,code_bss,bss_id,niveau_nappe_eau,mode_obtention,nom_producteur,latitude,longitude,sunrise,sunset,daylight_duration,precipitation_sum,shortwave_radiation_sum,et0_fao_evapotranspiration,cloud_cover_mean,pressure_msl_mean,wind_speed_10m_mean,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean
date_index,,,,,,,,,,,,,,,,,,
2017-01-01,10906X0039/C2-1,BSS002MNYD,101.85,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-01T07:19,2017-01-01T16:26,32800.70,0.0,7.88,0.95,47,1024.5,5.3,0.244,9.2
2017-01-02,10906X0039/C2-1,BSS002MNYD,101.89,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-02T07:19,2017-01-02T16:27,32850.58,0.0,4.29,0.56,93,1022.0,4.6,0.244,9.2
2017-01-03,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-03T07:19,2017-01-03T16:28,32904.28,0.0,8.02,1.59,3,1023.5,11.8,0.244,8.9
2017-01-04,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-04T07:19,2017-01-04T16:29,32961.75,0.0,8.08,2.52,5,1022.9,25.2,0.244,8.8
2017-01-05,10906X0039/C2-1,BSS002MNYD,102.01,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-05T07:19,2017-01-05T16:30,33022.91,0.0,6.93,2.07,14,1026.5,30.5,0.243,8.7

In [209]:
df.isna().sum()

code_bss                            0
bss_id                              0
niveau_nappe_eau                    0
mode_obtention                      0
nom_producteur                      0
latitude                            0
longitude                           0
sunrise                             0
sunset                              0
daylight_duration                   0
precipitation_sum                   0
shortwave_radiation_sum             0
et0_fao_evapotranspiration          0
cloud_cover_mean                    0
pressure_msl_mean                   0
wind_speed_10m_mean                 0
soil_moisture_0_to_100cm_mean       0
soil_temperature_0_to_100cm_mean    0
dtype: int64

In [210]:
# Shows duplicated rows for a date
print("Duplicated dates: ", df.index.duplicated().sum())
df[df.index.duplicated(keep=False)].sort_index()

# Keep only one reading per day
df = df[~df.index.duplicated(keep="first")]

# Check for actual date gaps
inferred = pd.infer_freq(df.index)
print("Detected frequency: ", inferred)  # should print 'D' if perfectly daily and gap-free
full_range = pd.date_range(df.index.min(), df.index.max(), freq="D")
missing_dates = full_range.difference(df.index)
print("Missing dates: ",len(missing_dates))
print(missing_dates[:37])

Duplicated dates:  3
Detected frequency:  None
Missing dates:  79
DatetimeIndex(['2019-09-20', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2024-05-12', '2024-05-13',
               '2024-05-14', '2024-05-15', '2024-05-16', '2024-05-17',
               '2024-05-18', '2024-05-19', '2024-05-20', '2024-05-21',
               '2024-05-22', '2024-09-10', '2024-09-11', '2024-09-12',
               '2024-09-13', '2024-09-14', '2024-09-15', '2024-09-16',
               '2024-09-17'],
              dtype='datetime64[us]', freq=None)

In [211]:
df.loc['2023-02-05']

code_bss                                                              10906X0039/C2-1
bss_id                                                                     BSS002MNYD
niveau_nappe_eau                                                                101.2
mode_obtention                                                         Valeur mesurée
nom_producteur                      Syndicat Mixte pour la Protection et la Gestio...
latitude                                                                    42.685696
longitude                                                                    2.685378
sunrise                                                              2023-02-05T06:59
sunset                                                               2023-02-05T17:07
daylight_duration                                                             36463.4
precipitation_sum                                                                 0.0
shortwave_radiation_sum                                                         11.39
et0_fao_evapotranspiration                                                       2.97
cloud_cover_mean                                                                   31
pressure_msl_mean                                                              1032.6
wind_speed_10m_mean                                                              30.3
soil_moisture_0_to_100cm_mean                                                   0.099
soil_temperature_0_to_100cm_mean                                                 10.3
Name: 2023-02-05 00:00:00, dtype: object

In [212]:
# Confirm series.index.freq prints 'D' 
series = df["niveau_nappe_eau"].sort_index().asfreq("D").interpolate()

print("Detected frequency: ",series.index.freq)     # should now print 'D'
print("Na dates: ", series.isna().sum())   # should be 0
missing_dates = full_range.difference(series.index)
print("Missing dates: ",len(missing_dates))
print(missing_dates[:10])

Detected frequency:  <Day>
Na dates:  0
Missing dates:  0
DatetimeIndex([], dtype='datetime64[us]', freq='D')

# Feature engineering

In [213]:
df.columns.tolist()

['code_bss',
 'bss_id',
 'niveau_nappe_eau',
 'mode_obtention',
 'nom_producteur',
 'latitude',
 'longitude',
 'sunrise',
 'sunset',
 'daylight_duration',
 'precipitation_sum',
 'shortwave_radiation_sum',
 'et0_fao_evapotranspiration',
 'cloud_cover_mean',
 'pressure_msl_mean',
 'wind_speed_10m_mean',
 'soil_moisture_0_to_100cm_mean',
 'soil_temperature_0_to_100cm_mean']

In [214]:
# Computation of the cumulative precipitation during the 7-30-90 last days
def cumulative_precipitation(df, days: int) -> pd.DataFrame:
    """
    Computation of the cumulative precipitation during the last 7-30-90 days
    """
    df[f'P_cum_{days}d'] = df['precipitation_sum'].rolling(window=days).sum()
    return df

def cumulative_eff_precipitation(df, days: int) -> pd.DataFrame:
    """
    Computation of the cumulative precipitation during the last 30-90 days minus 
    the et0_fao_evapotranspiration (mining the evaporation)
    """
    df[f'Peff_cum_{days}d'] = (df['precipitation_sum'] - df['et0_fao_evapotranspiration']).rolling(window=days).sum()
    return df

def mean_temp(df, days: int) -> pd.DataFrame:
    """
    Computation of the temperature mean on the last x days
    """
    df[f'Temperature_mean_{days}d'] = round(df['soil_temperature_0_to_100cm_mean'].rolling(window=days).mean(), 2)
    return df

In [238]:
cumulative_precipitation(df, days = 7)
cumulative_precipitation(df, days = 30)
cumulative_precipitation(df, days = 90)
cumulative_eff_precipitation(df, days = 30)
cumulative_eff_precipitation(df, days = 90)
mean_temp(df, days = 30)
display(df.head(10))
print("Shape of the df:", df.shape)

,code_bss,bss_id,niveau_nappe_eau,mode_obtention,nom_producteur,latitude,longitude,sunrise,sunset,daylight_duration,...,pressure_msl_mean,wind_speed_10m_mean,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean,P_cum_7d,P_cum_30d,P_cum_90d,Peff_cum_30d,Peff_cum_90d,Temperature_mean_30d
date_index,,,,,,,,,,,,,,,,,,,,,
2017-01-01,10906X0039/C2-1,BSS002MNYD,101.85,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-01T07:19,2017-01-01T16:26,32800.70,...,1024.5,5.3,0.244,9.2,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-02,10906X0039/C2-1,BSS002MNYD,101.89,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-02T07:19,2017-01-02T16:27,32850.58,...,1022.0,4.6,0.244,9.2,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-03,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-03T07:19,2017-01-03T16:28,32904.28,...,1023.5,11.8,0.244,8.9,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-04,10906X0039/C2-1,BSS002MNYD,101.98,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-04T07:19,2017-01-04T16:29,32961.75,...,1022.9,25.2,0.244,8.8,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-05,10906X0039/C2-1,BSS002MNYD,102.01,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-05T07:19,2017-01-05T16:30,33022.91,...,1026.5,30.5,0.243,8.7,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-06,10906X0039/C2-1,BSS002MNYD,102.05,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-06T07:19,2017-01-06T16:31,33087.68,...,1029.7,17.9,0.242,8.5,NaN,NaN,NaN,NaN,NaN,NaN
2017-01-07,10906X0039/C2-1,BSS002MNYD,102.12,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-07T07:19,2017-01-07T16:32,33155.99,...,1029.8,14.2,0.242,8.1,0.0,NaN,NaN,NaN,NaN,NaN
2017-01-08,10906X0039/C2-1,BSS002MNYD,102.14,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-08T07:19,2017-01-08T16:33,33227.75,...,1027.5,29.4,0.242,8.4,0.0,NaN,NaN,NaN,NaN,NaN
2017-01-09,10906X0039/C2-1,BSS002MNYD,102.15,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-09T07:19,2017-01-09T16:34,33303.06,...,1025.4,24.5,0.242,8.7,0.0,NaN,NaN,NaN,NaN,NaN
2017-01-10,10906X0039/C2-1,BSS002MNYD,102.14,Valeur reconstituée,Syndicat Mixte pour la Protection et la Gestio...,42.685696,2.685378,2017-01-10T07:18,2017-01-10T16:35,33382.75,...,1014.4,20.0,0.242,8.8,4.2,NaN,NaN,NaN,NaN,NaN

Shape of the df: (3402, 24)

In [240]:
df["P_cum_7d"]              = df["P_cum_7d"].fillna(df["P_cum_7d"].dropna().iloc[0])
df["P_cum_30d"]             = df["P_cum_30d"].fillna(df["P_cum_30d"].dropna().iloc[0])
df["P_cum_90d"]             = df["P_cum_90d"].fillna(df["P_cum_90d"].dropna().iloc[0])
df["Peff_cum_30d"]           = df["Peff_cum_30d"].fillna(df["Peff_cum_30d"].dropna().iloc[0])
df["Peff_cum_90d"]          = df["Peff_cum_90d"].fillna(df["Peff_cum_90d"].dropna().iloc[0])
df["Temperature_mean_30d"]  = df["Temperature_mean_30d"].fillna(df["Temperature_mean_30d"].dropna().iloc[0])

In [241]:
df.isnull().sum()

code_bss                            0
bss_id                              0
niveau_nappe_eau                    0
mode_obtention                      0
nom_producteur                      0
latitude                            0
longitude                           0
sunrise                             0
sunset                              0
daylight_duration                   0
precipitation_sum                   0
shortwave_radiation_sum             0
et0_fao_evapotranspiration          0
cloud_cover_mean                    0
pressure_msl_mean                   0
wind_speed_10m_mean                 0
soil_moisture_0_to_100cm_mean       0
soil_temperature_0_to_100cm_mean    0
P_cum_7d                            0
P_cum_30d                           0
P_cum_90d                           0
Peff_cum_30d                        0
Peff_cum_90d                        0
Temperature_mean_30d                0
dtype: int64

In [218]:
df.columns.tolist()

['code_bss',
 'bss_id',
 'niveau_nappe_eau',
 'mode_obtention',
 'nom_producteur',
 'latitude',
 'longitude',
 'sunrise',
 'sunset',
 'daylight_duration',
 'precipitation_sum',
 'shortwave_radiation_sum',
 'et0_fao_evapotranspiration',
 'cloud_cover_mean',
 'pressure_msl_mean',
 'wind_speed_10m_mean',
 'soil_moisture_0_to_100cm_mean',
 'soil_temperature_0_to_100cm_mean',
 'P_cum_7d',
 'P_cum_30d',
 'P_cum_90d',
 'Peff_cum_30d',
 'Peff_cum_90d',
 'Temperature_mean_30d']

In [242]:
output_path = Path('..') / 'data' / 'interim' / 'featured_data.csv'

df.to_csv(output_path)